### ISSUE TITLE
Homepage link in pypi 404

### ISSUE THREAD

**Issue by mic159** [ubernostrum/pwned-passwords-django#2]
The github/homepage link in [pypi](https://pypi.org/project/pwned-passwords-django/) hits a 404 because the project name is incorrect.

https://github.com/ubernostrum/pwned-passwords-django/blob/6ccd2dcdd25e3987c34e5a3c6027b46bed3614b0/setup.py#L18

Wrong: http://github.com/ubernostrum/django-pwned-passwords/
Correct: https://github.com/ubernostrum/pwned-passwords-django/

Please consider fixing the link, and pointing to https, not http :)

Side note: maybe you could also consider updating the README to include a link to pypi? or a basic pip install line to help people go from Github -> pypi.

**Comment by ubernostrum** [comment]
This got fixed in the just-merged package reorg.
