### ISSUE TITLE
Drop support for Python 3.7 and update minimum httpx

### ISSUE THREAD

**Issue by StevenMapes** [ubernostrum/pwned-passwords-django#41]
Since Python 3.7 is EOL and has been for a few months I think it's worth dropping support for it from this project and updating httpx to the latest 0.25 version which also drops Python 3.7 as well as including new additions and bug fixes. Hopefully httpx will also be updated soon to show support for Python 3.12 and httpcore version 1.0.0

**Comment by ubernostrum** [comment]
Dropping support for 3.7 will happen automatically the next time I do a release.
