### ISSUE TITLE
Acceptable use policy - User Agent

### ISSUE THREAD

**Issue by mic159** [ubernostrum/pwned-passwords-django#6]
I think the user-agent needs to be more specific than `python-requests/{version}` to comply with the acceptable use policy of the API.

Specifically:

> Things that are not awesome include:
> - Not properly identifying the user agent such that it accurately describes the consumer of the API

See: https://haveibeenpwned.com/API/v2#UserAgent
See: https://haveibeenpwned.com/API/v2#AcceptableUse

I propose setting it to something like:
`Django pwned password validator (https://github.com/ubernostrum/pwned-passwords-django)`

It would be even more awesome if you can override it with a setting in the `OPTIONS` dictionary like in #5 
That way people can set it to the name of their website, as they are the actual consumers of the API.

**Comment by ubernostrum** [comment]
I just committed a tweak to do a custom user-agent. Format includes pwned-passwords-django version, Python version and Django version in use. I may tweak it a bit before pushing an actual release containing the code, though; it might be useful to have the `requests` version for diagnosing bad behavior.

**Comment by mic159** [comment]
Nice, looks good.
