### ISSUE TITLE
Make the request timeout configurable

### ISSUE THREAD

**Issue by jarshwah** [ubernostrum/pwned-passwords-django#7]
We're consistently hitting the request timeout in production. Troy Hunt is investigating on his end why some of the requests are so slow - but it'd be useful to us if we could configure the request timeout for situations like this.

![pwned-timeouts](https://user-images.githubusercontent.com/541083/40596249-06c38992-627d-11e8-9380-06edb78f11b9.png)

**Comment by ubernostrum** [comment]
Let me know what you think of 1141c8d267a51a35207e1b7cea5ce4a4a4c3dddb.

**Comment by jarshwah** [comment]
Looks good! Timeout comment might need an update though. Sorry, on mobile
and not authed to comment directly.
